// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_shift(t,e,s){var i=jQuery,n=i(this),o=(s.find("li"),s.find(".ws_list")),d={position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden"},a=i("<div>").addClass("ws_effect ws_shift").css(d).appendTo(s),f=i("<div>").css(d).css({display:"none",zIndex:4}).appendTo(a),l=i("<div>").css(d).css({display:"none",zIndex:3}).appendTo(a);this.go=function(d,a,h){var p=s.width(),r=s.height();f.append(i(e.get(d)).clone()),l.append(i(e.get(a)).clone()),t.responsive<3&&(f.find("img").css("width","100%"),l.find("img").css("width","100%")),o.stop(!0,!0).hide().css({left:-d+"00%"});var c={left:[{left:-p},{left:0}],right:[{left:p},{left:0}],down:[{top:r},{top:0}],up:[{top:-r},{top:0}]}[t.direction||["left","right","down","up"][Math.floor(4*Math.random())]];t.support.transform&&(c[0].left?c[0]={translate:[c[0].left,0,0]}:c[0]={translate:[0,c[0].top,0]},c[1]={translate:[0,0,0]}),f.show(),l.show(),wowAnimate(f,c[0],c[1],t.duration,"easeInOutCubic",function(){o.show(),f.hide().html(""),l.hide().html(""),n.trigger("effectEnd")}),wowAnimate(l,{scale:1},{scale:.5},t.duration,"easeInOutCubic")}}jQuery.extend(jQuery.easing,{easeInOutCubic:function(t,e,s,i,n){return(e/=n/2)<1?i/2*e*e*e+s:i/2*((e-=2)*e*e+2)+s}});